---
- hosts: all
  sudo: true
  vars:
    server_name: "{{ ansible_eth1.ipv4.address }}"
    sys_packages: ['curl', 'vim', 'htop']
    video_packages: ['ffmpeg', 'libx264-120', 'x264', 'libfaac0', 'libavcodec-extra-53']
    php_packages: ['php5-curl', 'php5-cli', 'php5-gd']
  tasks:
    - include: tasks/init.yml
    - include: tasks/php.yml
    - include: tasks/video.yml